# National risk config file

national_risk:
  dataset: "inform-risk-index-2021"
  format: "xlsx"
  xlsx2csv: True
  sheet: "INFORM Risk 2025 (a-z)"
  headers: 2
  source_date:
    start: "01/01/2025"
    end: "31/12/2025"
