wfp_currency:
  name: "currency"
  dataset_suffix: "food-price"
  resource: "Global Food Security, Nutrition & Poverty: Currency"

wfp_commodity:
  dataset_suffix: "food-price"
  resource: "Global Food Security, Nutrition & Poverty: Commodities"

wfp_market:
  dataset_suffix: "food-price"
  resource: "Global Food Security, Nutrition & Poverty: Markets"
